/**
 * Lesson content structure types
 *
 * These types define the exact structure that LLMs should generate when creating lessons.
 * The structure is designed to be:
 * - Clear and unambiguous for LLM prompt engineering
 * - Easy to validate programmatically
 * - Flexible enough for various lesson types
 * - Structured for rendering in the UI
 */

/**
 * Metadata about the lesson
 */
export interface LessonMetadata {
  /**
   * The title of the lesson
   */
  title: string;

  /**
   * List of topics covered in the lesson
   */
  topics: string[];

  /**
   * Estimated time to complete the lesson in minutes
   */
  estimatedDuration: number;

  /**
   * Optional description of the lesson
   */
  description?: string;

  /**
   * Difficulty level
   */
  difficulty?: 'beginner' | 'intermediate' | 'advanced';
}

/**
 * Types of sections that can appear in a lesson
 */
export type LessonSectionType = 'introduction' | 'content' | 'exercise' | 'quiz' | 'summary';

/**
 * A single section within a lesson
 */
export interface LessonSection {
  /**
   * Unique identifier for the section
   */
  id: string;

  /**
   * Type of section (determines rendering and validation rules)
   */
  type: LessonSectionType;

  /**
   * Title of the section
   */
  title: string;

  /**
   * Main content of the section (markdown supported)
   */
  content: string;

  /**
   * Order in which the section appears (0-indexed)
   */
  order: number;

  /**
   * Optional metadata specific to section type
   * - For 'quiz': could contain questions array
   * - For 'exercise': could contain starter code
   * - For 'content': could contain code examples
   */
  metadata?: Record<string, unknown>;
}

/**
 * Complete lesson content structure
 *
 * This is the top-level structure that:
 * - Is stored in the database as JSONB
 * - Is generated by AI LLM clients
 * - Is validated by LessonContentValidator
 * - Is rendered in the UI
 */
export interface LessonContent {
  /**
   * Metadata about the lesson
   */
  metadata: LessonMetadata;

  /**
   * Sections that make up the lesson content
   * Must be ordered by the 'order' field
   */
  sections: LessonSection[];
}

/**
 * Validation rules for lesson content
 *
 * These rules define what makes a lesson "valid":
 * - Must have at least one section
 * - Must have at least one of: introduction, content, or summary
 * - Sections must have sequential order starting from 0
 * - All required fields must be present and non-empty
 */
export interface LessonContentValidationRules {
  minSections: number;
  requiredSectionTypes: LessonSectionType[];
  maxTitleLength: number;
  minContentLength: number;
}

/**
 * Default validation rules
 */
export const DEFAULT_LESSON_VALIDATION_RULES: LessonContentValidationRules = {
  minSections: 1,
  requiredSectionTypes: ['introduction'],
  maxTitleLength: 200,
  minContentLength: 10,
};
